### ISSUE TITLE
类型为decimal 的实体属性没有在 rafyentity.js 中生成

### ISSUE THREAD

**Issue by xubaotong** [zgynhqf/Rafy#105]
由于数字计算精度问题，须使用decimal计算。由于rafy前端实体为decimal的字段不能生成，使得字段不能修改后保存。

**Comment by zgynhqf** [comment]
不太明白你这个问题。
你是希望前端也使用 decimal 类型来进行计算吗？还是说后端在实体的属性使用的 decimal 来定义就可以了？
现在后段的实体应该是可以使用这个类型的定义属性的。而前段的 js 中使用的是 number 类型。这样会有什么问题吗？

**Comment by zgynhqf** [comment]
建议把关键的代码的截图提交一下。

**Comment by xubaotong** [comment]
实体 类型为 decimal 时 生成的rafyentityjs 中无相关项。
eg：entity 为goods ， price：decimal ， amount：double；
生成的 entityjs 中的 model： goods没有 price。
原因：处理逻辑 没有处理 decimal类型。
类似的 float 类型也没有处理。
参见： ServerTypeHelper 类 GetServerType 方法

**Comment by zgynhqf** [comment]
现在理解了。确实有这个问题。
标记为bug，1号优先级，尽快修改。

**Comment by dyancl1024** [comment]
预计9月7号解决

**Comment by dyancl1024** [comment]
sql server 有 tinyint类型 没有byte类型  跑单元测试时映射数据库报错，oracle也没有byte类型用number来做映射，
