### ISSUE TITLE
查询参数中带有 单引号，Rafy在执行查询时会出现异常

### ISSUE THREAD

**Issue by xujianshe** [zgynhqf/Rafy#108]

**Comment by zgynhqf** [comment]
请把相关代码及截图提交一下，谢谢

**Comment by xujianshe** [comment]
调用代码图片：https://static.dingtalk.com/media/lALPAAAAAQ0T5S_Mt80D5A_996_183.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%2272872932%3A134992807%22%2C%22msgId%22%3A%2233153947597%22%7D&open_id=72872932

参数：
https://static.dingtalk.com/media/lALPAAAAAQzXtp3Mqs0DSQ_841_170.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%2272872932%3A134992807%22%2C%22msgId%22%3A%2233153952333%22%7D&open_id=72872932


异常信息：
Incorrect syntax near 'sGmbH'.
Unclosed quotation mark after the character string ') AND [T0].[TaxCode] IN (',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',',') AND [T0].[DBI_IsPhantom] = @p1
ORDER BY [T0].[Id] ASC'.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& use

**Comment by zgynhqf** [comment]
看到图了。是 in 语句的参数中有分号是吧？

**Comment by xujianshe** [comment]
不是， 是有个外国客户名称中带有 单引号   比如参数中有这个名字： Shrimper'sGmbh LiangXu

**Comment by zgynhqf** [comment]
生成的 sql 发出来看一下。

**Comment by xujianshe** [comment]
SELECT *
FROM [T_Customer] AS [T0]
WHERE [T0].[TenantId] = '25' AND [T0].[Name] IN ('通标标准技术服务有限公司宁波分公司','大连雅立峰生物制药有限公司','北京复星医药科技开发有限公司','北京复星医药科技开发有限公司','北京复星医药科技开发有限公司','成都市环境保护科学研究院','成都市环境保护科学研究院','太仓丽盛制版有限公司','郑凡','重庆爱普特电器有限公司','重庆爱普特电气有限公司','重庆艾普特电气有限公司','六安明都房地产开发有限公司舒城分公司','Shrimper'sGmbH LiangXu','华福证券有限责任公司西宁五四西路证券营业部','华福证券有限责任公司西北分公司','上海邑嘉信息技术有限公司','北京超星尔雅教育科技有限公司','宁波爱贝丽运动用品有限公司','温州市华顺石油化工有限公司','个人','亘喜生物科技（上海）有限公司','汕头拉飞逸时装有限公司','个人','汕头拉飞逸时装有限公司','CAPM EUROPE FRANCE','瑞安市瑾南汽摩部件有限公司','上海炫林日用品有限公司','合肥颂智商贸有限公司','自贡市蜀光中学','海安县住房和城乡建设局','广东中南亚太科技管理有限公司','西藏信投安银投资管理有限公司','上海后藤金属制品有限公司','江阴市洸洋塑业有限公司','国富融资租赁（上海）有限公司','建湖县高新区','华福证券有限责任公司兰州庆阳路证券营业部','华福证券有限责任公司兰州庆阳路证券营业部','大昌华嘉商业（中国）有限公司','武汉苏泊尔炊具有限公司','山东省博兴县天元购物广场有限公司','上海金虹桥商务广场管理有限公司','正文科技股份有限公司','长兴博弈股权投资基金管理中心（有限合伙）','河南开心一方置地集团有限公司','晋城经济技术开发区管委会','晋城经济技术开发区管委会','卓细（深圳）科技有限公司','北京火星盒子科技有限公司','福建融诚德润股权投资管理有限公司','草根同创资本（北京）有限公司','个人','中山市佳雪生活电器','中山市佳雪生活电器','上海新小信息科技有限公司','沈阳中荣印刷有限公司','维亨股份有限公司','上海基越工业设备有限公司','徐州矿务集团总医院','狄长华','徐矿二院','徐矿一院','河南省郑州市中州文化交流协会','草根同创资本（北京）有限公司','宿迁市钟吾医院有限责任公司','安徽济民肿瘤医院','狮桥融资租赁（中国）有限公司','上海吾爱庐文化传播发展有限公司','杭州博达化工科技发展有限公司','上海通帛交通施设工程有限公司','河南华通新材料有限公司','河南华通新材料有限公司','CHILISIN ELECTRONICS CORP.','淮安大田房地产开发有限公司','德州立天唐人置业有限公司','北京复星医药科技开发有限公司','爱绿幼儿园','宋彦','上海金虹桥商务广场管理有限公司','上海真良阁文化传播有限公司','深圳市新辉鸿机电有限公司','上海艾想投资有限公司','温州老年病医院有限公司','辽宁省大连市中级人民法院','Yoshihiko','广西嘉路人力资源顾问有限责任公司','歙县瑞海机电销售有限公司','台湾瑞普有限公司','个人','广州要玩娱乐网络技术有限公司','日铁住金物产（株）','玉林市第一人民医院','建湖县高新区','北京三赢伟业科技有限公司','北京腾信创新网络营销技术股份有限公司','弘廷（杭州）厨柜贸易有限公司','张振举','北京艺星医疗美容医院有限公司','北京自如生活资产管理有限公司','上海众吴商贸有限公司','个人','上海新番资产管理有限公司','伊太空设计咨询（上海）有限公司','北京供销大数据集团股份有限公司','东莞市安德标签材料有限公司','M-telligent','苏州蓝可创电子科技有限公司','杭州典玺网络科技有限公司','北京城乡建设集团有限责任公司','成都炽城科技有限公司','埃瑞巴蒂成都科技有限公司','正文科技股份有限公司','杭州米琪科技有限公司','共青城市科技工贸和信息化委员会','杭州易济商务咨询有限公司','杭州易济商务咨询有限公司','广州市讯光信息科技有限责任公司','广州市讯光信息科技有限责任公司','登辰网络技术有限公司','杭州恩牛网络技术有限公司','安富利电子科技（中国）有限公司','安富利电子科技（中国）有限公司','个人','自贡市新新嘉园酒店管理有限公司','上海保油新能源科技有限公司','上海保油新能源科技有限公司','北京飞逸网络科技有限公司','浙江科尔健轻工机械有限公司','成田制陶所','北京飞逸网络科技有限公司','杭州丽水商会起市分会','浙江天正电气股份有限公司','郑州市富连网电子科技有限公司深圳分公司','北京飞逸网络科技有限公司','苏州昇泰商务咨询有限公司','个人','南通意阳国际贸易有限公司','南浔区政府办公室','上海侨福外高桥置业有限公司','北京飞逸网络科技有限公司','遊戲新幹線科技股份有限公司','深圳市龙游世纪科技有限公司','江苏大富豪啤酒有限公司','上海野藤科技信息发展有限公司','太仓丽盛制版有限公司','浙江东冠信息技术有限公司','镇江悦乐网络科技有限公司','好乐紫外技术贸易（上海）有限公司','深圳市方大建科集团有限公司','嘉善淞浩金属材料有限公司','福州彼此一百营销顾问有限公司','上海比华利医疗美容门诊有限公司','无锡虎虎机电科技有限公司','上海诚诣建筑装潢有限公司','布罗数据科技（宁波）有限公司','王小红','北京飞逸网络科技有限公司','武汉光庭信息技术股份有限公司','北京飞逸网络科技有限公司','常熟中纺金顶时尚设计顾问有限公司','常熟中纺金顶时尚设计顾问有限公司','兰州海华房地产开发有限公司','威雅利电子（香港）有限公司驻厦门代表处','新疆金泰运商贸有限公司','上海要娱网络技术有限公司','广州要娱网络技术有限公司','上海钰翔国际贸易有限公司','上海涌玉文化传播有限公司','CAPMEUROPEFRANCE','安捷尔外包服务（上海）有限公司','厦门优他动漫科技有限公司','铭普思建筑工程咨询（上海）有限公司','德国耶拿分析仪器股份公司北京代表处','德国耶拿分析仪器股份公司北京代表处','深圳大学','深圳大学','上海蕤熙实业有限公司','黄平','靖江宝丰冶金科技有限公司','浙江省温州市公安局交警支队一大队','笑旺商贸（上海）有限公司','大连原创设计工程有限公司','北京当代互娱国际文化传媒有限公司','河南开心一方置地集团有限公司','德国耶拿分析仪器股份公司北京代表处','六安明都房地产开发有限公司舒城分公司','靖江宝丰冶金科技有限公司','苏州市弘笑网络科技有限公司','昆山禹童房地产咨询有限公司','北京磐谷创业投资有限责任公司','赣州市美陈文化传播有限公司','亚朵（上海）酒店管理有限公司','北京易能智达电子有限公司','无锡合优商贸有限公司','江苏易乐网络科技有限公司','义乌市盈茀资产管理有限公司','广州千淘信息技术有限公司','杭州赛诺华新材料科技有限公司','上海领音文化传播有限公司') AND [T0].[TaxCode] IN ('','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','') AND [T0].[DBI_IsPhantom] = 0
ORDER BY [T0].[Id] ASC;

**Comment by xujianshe** [comment]
其中在 IN参数中 有个用户名叫：'Shrimper'sGmbH LiangXu'

**Comment by zgynhqf** [comment]
果然是 in 语句有问题。

**Comment by zhuwansu** [comment]
预计 8月 11

**Comment by zgynhqf** [comment]
@zhuwansu 
是9月11号吗？
