### ISSUE TITLE
由TransactionScope指定事务孤立级别

### ISSUE THREAD

**Issue by zhuwansu** [zgynhqf/Rafy#166]
源码：/// <summary>
		/// 通过数据库配置名的代理：实体仓库，构造一个 单连接事务块。
		/// </summary>
		/// <param name="dbSetting">整个数据库的配置名</param>
		/// <param name="level">事务的孤立级别</param>
		/// <returns></returns>
		public static SingleConnectionTransactionScope TransactionScope(DbSetting dbSetting, IsolationLevel level)
		{
			return new SingleConnectionTransactionScope(dbSetting);
		}
应修改为 return new SingleConnectionTransactionScope(dbSetting,level);

**Comment by zgynhqf** [comment]
已经修复。
下次你可直接用 PullRequest 提交这个代码。
