### ISSUE TITLE
反序列化碰到默认值不更新问题，看下面吧，留个念

### ISSUE THREAD

**Issue by ctmb520** [zgynhqf/Rafy#200]
`/// <summary>
        /// 反序列化成对像
        /// </summary>
        /// <param name="type">typeof(object)</param>
        /// <param name="json">字符串</param>
        /// <returns></returns>
        public static IDomainComponent ToJsonRafy(this string json, Type type)
        {
            var deserializer = new AggtDeserializer();
            deserializer.UpdatedEntityCreationMode = UpdatedEntityCreationMode.RequeryFromRepository;
            return deserializer.Deserialize(type, json);
        }`

**Comment by zgynhqf** [comment]
deserializer.UpdatedEntityCreationMode = UpdatedEntityCreationMode.RequeryFromRepository;

**Comment by zgynhqf** [comment]
如果无法完全控制所有属性的值和状态，最好都使用 RequeryFromRepository 模式。
