### ISSUE TITLE
remove the ISerializable interface from ManagedPropertyObject

### ISSUE THREAD

**Issue by BachelorEric** [zgynhqf/Rafy#22]
remove the ISerializable interface from ManagedPropertyObject, use OnSerializingAttribute/OnDeserializedAttribute to mark the methods and Serialize values into Hashtable, so you can remove the serialization constructor from all entities.

System.Collections.Hashtable values;

        [OnSerializing()]
        void OnSerializingMethod(StreamingContext context)
        {
            values = new System.Collections.Hashtable();
            //values = new Dictionary<string, object>();
            //只序列化非默认值的编译期属性, 不序列化运行时属性
            foreach (var field in this._compiledFields)
            {
                if (field.HasValue)
                {
                    var property = field.Property;

                    var meta = property.GetMeta(this);
                    if (meta.Serializable)
                    {
                        var value = field.Value;
                        if (!object.Equals(value, meta.DefaultValue))
                        {
                            values.Add(property.Name, value);
                        }
                    }
                }
            }
        }

        void OnDeserialization()
        {
            values.OnDeserialization(this);
            var compiledProperties = this.PropertiesContainer.GetNonReadOnlyCompiledProperties();

            this.InitFields(compiledProperties);

            var clrFields = FieldsSerializationHelper.EnumerateSerializableFields(GetType());

            //遍历所有已经序列化的属性值序列
            var compiledPropertiesCount = compiledProperties.Count;

            for (int i = 0; i < compiledPropertiesCount; i++)
            {
                var property = compiledProperties[i];

                if (values.ContainsKey(property.Name))
                {
                    this._LoadProperty(property, values[property.Name]);
                }
            }
        }

        [OnSerialized()]
        void OnSerializedMethod(StreamingContext context)
        {
        }

        [OnDeserializing()]
        void OnDeserializingMethod(StreamingContext context)
        {
        }

        [OnDeserialized()]
        void OnDeserializedMethod(StreamingContext context)
        {
            OnDeserialization();
            if (this._compiledFields == null)
            {
                this.InitFields();
            }

            this.OnDeserialized(null as DesirializedArgs);
        }

**Comment by BachelorEric** [comment]
Performance test:
20170116084402366:Binary Serialize Size:3721582bytes,EntityList.Count=10000 
20170116084402367:Binary Serialize:410ms
20170116084402970:Binary Deserialize:603ms
20170116084430098:Binary Serialize Size:3721582bytes,EntityList.Count=10000 
20170116084430098:Binary Serialize:431ms
20170116084430702:Binary Deserialize:602ms
20170116084622230:Binary Serialize Size:3721582bytes,EntityList.Count=10000 
20170116084622231:Binary Serialize:426ms
20170116084622768:Binary Deserialize:537ms
20170116085720266:Binary Serialize Size:18601582bytes,EntityList.Count=50000 
20170116085720266:Binary Serialize:2212ms
20170116085725049:Binary Deserialize:4782ms
20170116085952626:Binary Serialize Size:18601582bytes,EntityList.Count=50000 
20170116085952626:Binary Serialize:2294ms
20170116085956945:Binary Deserialize:4319ms
20170116094427113:Binary Serialize Size:18601582bytes,EntityList.Count=50000 
20170116094427114:Binary Serialize:2064ms
20170116094430756:Binary Deserialize:3642ms
20170116094456595:Binary Serialize Size:18601582bytes,EntityList.Count=50000 
20170116094456596:Binary Serialize:2350ms
20170116094500152:Binary Deserialize:3556ms
20170116094520702:Binary Serialize Size:18601582bytes,EntityList.Count=50000 
20170116094520702:Binary Serialize:2189ms
20170116094524326:Binary Deserialize:3624ms
20170116094639439:Binary Serialize Size:18601582bytes,EntityList.Count=50000 
20170116094639440:Binary Serialize:2182ms
20170116094643215:Binary Deserialize:3775ms

**Comment by zgynhqf** [comment]
其实我记得现在的框架已经实现了这两个接口了。构造器好像无法优化掉，你可以试一试。
另外，下一个版本中，会解决掉这个问题。后续的版本会支持 NET CORE，不再考虑二进制序列化。

PS:怎么自己关了这个问题了？
