### ISSUE TITLE
Linq 支持的操作需要更加全面。

### ISSUE THREAD

**Issue by HuKang183** [zgynhqf/Rafy#41]
rafy查询linq支持的操作符太少，我们经常会用到group但是rafy不支持。
还有就是在构建查询条件的时候比如
q = q.Where(e => e.Name.equire(a));
q = q.Where(e => e.Name.equire(b));
如果是或者 这个2条语句好像不能分开写只能q = q.Where(e => e.Name.equire(b)||e.Name.equire(a));
也就是q只能以 &&符号相加 不能以 ||符号相加

好了我今天就先说这么多！

**Comment by zgynhqf** [comment]
可以使用 q = q.Where(e => e.Name.Equals(b) && e.Name.Equals(a)); 此类语法。
没有这个问题。
