### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by gdnyfcuso** [zgynhqf/Rafy#44]
1orm能不能独立化
2rafy能不能做为云平台的基础框架
3属性系统是怎么设计出来的
4如果去掉属性系统rafy的方便之处在哪里
5属性系统能不能替换成更好用的方式

**Comment by zgynhqf** [comment]
第五个问题见：#40

**Comment by zgynhqf** [comment]
第三、四个问题：见：
[实体扩展属性系统-系统设计说明书.pdf](http://files.cnblogs.com/files/zgynhqf/%E5%AE%9E%E4%BD%93%E6%89%A9%E5%B1%95%E5%B1%9E%E6%80%A7%E7%B3%BB%E7%BB%9F-%E7%B3%BB%E7%BB%9F%E8%AE%BE%E8%AE%A1%E8%AF%B4%E6%98%8E%E4%B9%A6.pdf)

**Comment by zgynhqf** [comment]
第二个问题：你的意思可能是表达想要自动支持多租户，并实现租户数据的自动隔离？
这样是可以的。已经提供了多租户的插件，未来将会开源。

**Comment by zgynhqf** [comment]
第一个问题：好建议，下一个版本中，会将 ORM 的实现作为外层的独立实现。同时可以实现多个 ORM 框架的对接。
