### ISSUE TITLE
AutoMigrate 会扫描用户的所有表

### ISSUE THREAD

**Issue by zhuwansu** [zgynhqf/Rafy#51]
`protected override void LoadAllColumns(Database database)
        {
            foreach (Table table in database.Tables)
            {
                using (var columnsReader = this.Db.QueryDataReader(
@"SELECT * FROM user_tab_columns WHERE TABLE_NAME = {0}",
table.Name))
                {
                    while (columnsReader.Read())
                    {
                        string columnName = columnsReader["COLUMN_NAME"].ToString();
                        string sqlType = columnsReader["DATA_TYPE"].ToString().ToUpper();
                        if (sqlType == "number")
                        {
                            var dataScale = columnsReader["DATA_SCALE"].ToString();
                            if (dataScale == "0") { sqlType = "integer"; }
                        }

                        DbType dbType = OracleDbTypeHelper.ConvertFromOracleTypeString(sqlType);
                        Column column = new Column(columnName, dbType, null, table);
                        column.IsRequired = columnsReader["NULLABLE"].ToString() == "N";

                        table.Columns.Add(column);
                    }

                    table.SortColumns();
                }
            }
        }`
it works will scan all tables of user 。

**Comment by zgynhqf** [comment]
不需要过滤。
Rafy 会维护好整个库的所有表。如果需要不维护多余的表的话，只需要禁用 DropTable 的选项即可，这时，框架是不会去删除这些表的。
