### ISSUE TITLE
ConverterFactory 需要更名为 DbConnectorFactory

### ISSUE THREAD

**Issue by zgynhqf** [zgynhqf/Rafy#61]
ConverterFactory 需要更名为 DbConnectorFactory。
此修改需要在 Master、NetStandard 上进行同步。

**Comment by wang9275483** [comment]
我目前在做修改。但不知道为什么提交到Issues里面了。正在研究

**Comment by wang9275483** [comment]
Master和NetStandard 都已经改好，并且提交

**Comment by mark620** [comment]
cool
