### ISSUE TITLE
实体字段非常多，数据量也很大。生成报表时，查询部分字段不支持；建议支持部分字段查询，为了节省资源使用DataReader参数返回数据，用户可灵活使用数据源构造数据

### ISSUE THREAD

**Issue by xubaotong** [zgynhqf/Rafy#67]

**Comment by zgynhqf** [comment]
查询时，基于 CQRS 理念，不需要返回实体。所以 Rafy 提供了表格类型数据的查询。
见：http://zgynhqf.github.io/Rafy/html/55180b16-9fda-42a1-8c4f-27d037aeae76.htm。
