### ISSUE TITLE
当Oracle字段保存是科学计数法的时候，rafy报指定的转换类型无效

### ISSUE THREAD

**Issue by gdnyfcuso** [zgynhqf/Rafy#72]
当Oracle字段保存是科学计数法的时候，rafy报指定的转换类型无效
数据保存的时候，被自动转成了 2.46989898989899E126 查询的时候报了
异常：System.InvalidCastException:“指定的转换无效。”

**Comment by zgynhqf** [comment]
如果是异常的话，请把 StackTrace 发上来。
最好能附带截图。

**Comment by zgynhqf** [comment]
请将 StackTrace 上传。否则无法定位问题所在。
将会关闭此问题。
