### ISSUE TITLE
Linq 查询中，单个 Boolean 属性的判断会有问题

### ISSUE THREAD

**Issue by zgynhqf** [zgynhqf/Rafy#80]
在 Rafy 的 Linq 查询模式中，当 Where、Any、All 等方法中的 Labmda 表达式中，出现对某个 bool 类型的属性的判断时，会出现异常。
例如：
Where(e => e.IsDefault)
Where(e => e.AggregateChildren.Concrete().Any(x => x.IsDefault))
上述两种情况，都会出现异常。

完成后，需要添加相应的两个单元测试。

**Comment by zgynhqf** [comment]
![image](https://user-images.githubusercontent.com/10123715/29739379-12b88ed2-8a6f-11e7-8c56-027ea6fdb85c.png)

**Comment by GuochaoWang** [comment]
Bug已修复，已提交PR。
