### ISSUE TITLE
幽灵插件：实体插件不需要引用该插件。

### ISSUE THREAD

**Issue by zgynhqf** [zgynhqf/Rafy#81]
见 http://www.cnblogs.com/zgynhqf/p/5086644.html 5楼评论。

**Comment by zhuwansu** [comment]
这个issue什么意思啊？引用了会有问题吗？

**Comment by zgynhqf** [comment]
想做成真正的 “插件”，就是即插即用。
例如 AccountsPlugin 没有引用 PhantomPlugin。当 PhantomPlugin 加入到应用程序中时，AccountsPlugin 中的 User 类型自动就实现了假删除。整个过程不需要修改 AccountsPlugin 中的任何代码。

**Comment by zgynhqf** [comment]
不过其实细想的话，就算不修改 AccountsPlugin 中的任何代码，为了区分哪些实体是需要假删除、哪些是不需要假删除的，也需要一些额外的配置。这个配置可以是文件型配置，也可以是代码配置。
所以目前完全可以通过添加一个优先级最低&最后启动的配置型插件、或者在组装插件时配置所有的实体，即可实现业务实体插件与幽灵插件的完全独立。

**Comment by zgynhqf** [comment]
本功能不再实现。
解决方案：通过添加一个优先级最低、最后启动的配置型插件（可同时引用业务实体插件及幽灵插件），又或者在 DomainApp 组装插件时，配置所有的实体，即可实现业务实体插件与幽灵插件的完全独立。
