### ISSUE TITLE
实体被删除后，状态应该为 New。

### ISSUE THREAD

**Issue by zgynhqf** [zgynhqf/Rafy#84]
修复以下单元测试：__ET_PersistenceStatus_Delete_SavedAsNew

**Comment by GuochaoWang** [comment]
查询了一下代码发现执行删除后会调用Rafy\Domain\Entity\Entity.Csla.cs类IDirtyAware.MarkSaved()方法修改实体的状态。方法中有关于这个问题的注释。从注释看实体删除后状体设置为PersistenceStatus.Unchanged了是未来避免一些问题。具体代码如下：

`
/// <summary>
/// 递归将整个组合对象树都标记为未变更状态。
/// </summary>
void IDirtyAware.MarkSaved()
{
	//聚合子需要都调用 MarkSaved。
	var enumerator = this.GetLoadedChildren();
	while (enumerator.MoveNext())
	{
		var child = enumerator.Current.Value;
		child.MarkSaved();
	}
	if (_treeChildren != null)
	{
		_treeChildren.MarkSaved();
	}

	this.PersistenceStatus = PersistenceStatus.Unchanged;

	#region 设计说明：Deleted 后的数据的状态不再改为 New

	/*********************** 代码块解释 *********************************
	 * Deleted 后的数据的状态不再改为 New，否则会出现两个问题：
	 * 1、实体列表在保存后，其中的某些项的状态是 New，整个列表的状态是 Dirty，会引起困惑，而且会引起再次保存会重复插入已经删除的数据的问题。
	 * 2、也不能依靠在实体列表删除该项的做法，这同样会引起困惑。同样，如果开发者没有保存列表，而是直接保存实体时，
	 * 同样会将状态为 New 的实体遗留在列表中。继续造成了第一条的问题。
	 * 
	 * 结论：
	 * 保持实体的状态的设计为一种简单易理解的状态，更易被开发者接受：
	 * - 三种实体的状态对应数据库的操作：（CDU）；
	 * - 这些状态的数据在保存后，都会变更到 Unchanged 的状态。
	 * - 不论实体的状态如何变换，都不会影响 EntityList 中的项的个数，除非直接操作 EntityList。
	 * - 删除后的实体，在保存后的状态是 Unchanged，同样表示这个实体已经持久化到数据库中（只不过持久化操作是删除）。
	 *      这时，如果再修改实体的属性时，状态会变更到 Modified。此类数据再进行保存，会因为数据库中没有相应的数据，而导致更新失效。
	 *      （如果是幽灵删除则会更新成功……）（当然，其实这种场景较少。）
	********************************************************************/

	////*********************** 代码块解释 *********************************
	// * 在保存删除的实体情况下，聚合子的状态需要在 MarkSaved 之后再设置为 New。
	// * 这是因为在删除某个聚合时，使用者只需要设置聚合根的 PersistenceStatus 为 Deleted，然后再保存，就可以把整个聚合删除。
	// * 但是这时，只有聚合父的状态为被设置为 Deleted，而聚合子的状态还是其它状态；导致 MarkSaved 之后，聚合子的状态不是 New。
	// * 
	// * 注意：需要先 MarkSaved，再设置为 New。这是因为 MarkSaved 需要有一些额外的操作。
	//**********************************************************************/
	////if (this.IsDeleted)
	////{
	////    (this as IDirtyAware).MarkAggregate(PersistenceStatus.New);
	////}
	////else
	////{
	////    this.PersistenceStatus = PersistenceStatus.Unchanged;
	////} 

	#endregion
}
`
